/*
TrueNAS RESTful API

Go SDK for interacting with TrueNAS APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
	"fmt"
)

// checks if the ISCSITargetExtent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ISCSITargetExtent{}

// ISCSITargetExtent struct for ISCSITargetExtent
type ISCSITargetExtent struct {
	Id     int32  `json:"id"`
	Target int32  `json:"target"`
	Lunid  *int32 `json:"lunid,omitempty"`
	Extent int32  `json:"extent"`
}

type _ISCSITargetExtent ISCSITargetExtent

// NewISCSITargetExtent instantiates a new ISCSITargetExtent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewISCSITargetExtent(id int32, target int32, extent int32) *ISCSITargetExtent {
	this := ISCSITargetExtent{}
	this.Id = id
	this.Target = target
	this.Extent = extent
	return &this
}

// NewISCSITargetExtentWithDefaults instantiates a new ISCSITargetExtent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewISCSITargetExtentWithDefaults() *ISCSITargetExtent {
	this := ISCSITargetExtent{}
	return &this
}

// GetId returns the Id field value
func (o *ISCSITargetExtent) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ISCSITargetExtent) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ISCSITargetExtent) SetId(v int32) {
	o.Id = v
}

// GetTarget returns the Target field value
func (o *ISCSITargetExtent) GetTarget() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *ISCSITargetExtent) GetTargetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *ISCSITargetExtent) SetTarget(v int32) {
	o.Target = v
}

// GetLunid returns the Lunid field value if set, zero value otherwise.
func (o *ISCSITargetExtent) GetLunid() int32 {
	if o == nil || IsNil(o.Lunid) {
		var ret int32
		return ret
	}
	return *o.Lunid
}

// GetLunidOk returns a tuple with the Lunid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ISCSITargetExtent) GetLunidOk() (*int32, bool) {
	if o == nil || IsNil(o.Lunid) {
		return nil, false
	}
	return o.Lunid, true
}

// HasLunid returns a boolean if a field has been set.
func (o *ISCSITargetExtent) HasLunid() bool {
	if o != nil && !IsNil(o.Lunid) {
		return true
	}

	return false
}

// SetLunid gets a reference to the given int32 and assigns it to the Lunid field.
func (o *ISCSITargetExtent) SetLunid(v int32) {
	o.Lunid = &v
}

// GetExtent returns the Extent field value
func (o *ISCSITargetExtent) GetExtent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Extent
}

// GetExtentOk returns a tuple with the Extent field value
// and a boolean to check if the value has been set.
func (o *ISCSITargetExtent) GetExtentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Extent, true
}

// SetExtent sets field value
func (o *ISCSITargetExtent) SetExtent(v int32) {
	o.Extent = v
}

func (o ISCSITargetExtent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ISCSITargetExtent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["target"] = o.Target
	if !IsNil(o.Lunid) {
		toSerialize["lunid"] = o.Lunid
	}
	toSerialize["extent"] = o.Extent
	return toSerialize, nil
}

func (o *ISCSITargetExtent) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"target",
		"extent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varISCSITargetExtent := _ISCSITargetExtent{}

	err = json.Unmarshal(bytes, &varISCSITargetExtent)

	if err != nil {
		return err
	}

	*o = ISCSITargetExtent(varISCSITargetExtent)

	return err
}

type NullableISCSITargetExtent struct {
	value *ISCSITargetExtent
	isSet bool
}

func (v NullableISCSITargetExtent) Get() *ISCSITargetExtent {
	return v.value
}

func (v *NullableISCSITargetExtent) Set(val *ISCSITargetExtent) {
	v.value = val
	v.isSet = true
}

func (v NullableISCSITargetExtent) IsSet() bool {
	return v.isSet
}

func (v *NullableISCSITargetExtent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableISCSITargetExtent(val *ISCSITargetExtent) *NullableISCSITargetExtent {
	return &NullableISCSITargetExtent{value: val, isSet: true}
}

func (v NullableISCSITargetExtent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableISCSITargetExtent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
