/*
TrueNAS RESTful API

Go SDK for interacting with TrueNAS APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
	"fmt"
)

// checks if the DeleteISCSIExtentParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteISCSIExtentParams{}

// DeleteISCSIExtentParams struct for DeleteISCSIExtentParams
type DeleteISCSIExtentParams struct {
	Remove bool `json:"remove"`
	Force  bool `json:"force"`
}

type _DeleteISCSIExtentParams DeleteISCSIExtentParams

// NewDeleteISCSIExtentParams instantiates a new DeleteISCSIExtentParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteISCSIExtentParams(remove bool, force bool) *DeleteISCSIExtentParams {
	this := DeleteISCSIExtentParams{}
	this.Remove = remove
	this.Force = force
	return &this
}

// NewDeleteISCSIExtentParamsWithDefaults instantiates a new DeleteISCSIExtentParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteISCSIExtentParamsWithDefaults() *DeleteISCSIExtentParams {
	this := DeleteISCSIExtentParams{}
	return &this
}

// GetRemove returns the Remove field value
func (o *DeleteISCSIExtentParams) GetRemove() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Remove
}

// GetRemoveOk returns a tuple with the Remove field value
// and a boolean to check if the value has been set.
func (o *DeleteISCSIExtentParams) GetRemoveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Remove, true
}

// SetRemove sets field value
func (o *DeleteISCSIExtentParams) SetRemove(v bool) {
	o.Remove = v
}

// GetForce returns the Force field value
func (o *DeleteISCSIExtentParams) GetForce() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Force
}

// GetForceOk returns a tuple with the Force field value
// and a boolean to check if the value has been set.
func (o *DeleteISCSIExtentParams) GetForceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Force, true
}

// SetForce sets field value
func (o *DeleteISCSIExtentParams) SetForce(v bool) {
	o.Force = v
}

func (o DeleteISCSIExtentParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteISCSIExtentParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["remove"] = o.Remove
	toSerialize["force"] = o.Force
	return toSerialize, nil
}

func (o *DeleteISCSIExtentParams) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"remove",
		"force",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteISCSIExtentParams := _DeleteISCSIExtentParams{}

	err = json.Unmarshal(bytes, &varDeleteISCSIExtentParams)

	if err != nil {
		return err
	}

	*o = DeleteISCSIExtentParams(varDeleteISCSIExtentParams)

	return err
}

type NullableDeleteISCSIExtentParams struct {
	value *DeleteISCSIExtentParams
	isSet bool
}

func (v NullableDeleteISCSIExtentParams) Get() *DeleteISCSIExtentParams {
	return v.value
}

func (v *NullableDeleteISCSIExtentParams) Set(val *DeleteISCSIExtentParams) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteISCSIExtentParams) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteISCSIExtentParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteISCSIExtentParams(val *DeleteISCSIExtentParams) *NullableDeleteISCSIExtentParams {
	return &NullableDeleteISCSIExtentParams{value: val, isSet: true}
}

func (v NullableDeleteISCSIExtentParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteISCSIExtentParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
