/*
TrueNAS RESTful API

Go SDK for interacting with TrueNAS APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
	"fmt"
)

// checks if the VM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VM{}

// VM struct for VM
type VM struct {
	Id                   int32            `json:"id"`
	Name                 string           `json:"name"`
	Description          *string          `json:"description,omitempty"`
	Vcpus                *int32           `json:"vcpus,omitempty"`
	Memory               *int32           `json:"memory,omitempty"`
	Autostart            *bool            `json:"autostart,omitempty"`
	Time                 *string          `json:"time,omitempty"`
	Bootloader           *string          `json:"bootloader,omitempty"`
	Cores                *int32           `json:"cores,omitempty"`
	Threads              *int32           `json:"threads,omitempty"`
	ShutdownTimeout      *int32           `json:"shutdown_timeout,omitempty"`
	Devices              []VMDevicesInner `json:"devices,omitempty"`
	Status               *VMStatus        `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VM VM

// NewVM instantiates a new VM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVM(id int32, name string) *VM {
	this := VM{}
	this.Id = id
	this.Name = name
	return &this
}

// NewVMWithDefaults instantiates a new VM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVMWithDefaults() *VM {
	this := VM{}
	return &this
}

// GetId returns the Id field value
func (o *VM) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VM) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VM) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *VM) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VM) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VM) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *VM) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *VM) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *VM) SetDescription(v string) {
	o.Description = &v
}

// GetVcpus returns the Vcpus field value if set, zero value otherwise.
func (o *VM) GetVcpus() int32 {
	if o == nil || IsNil(o.Vcpus) {
		var ret int32
		return ret
	}
	return *o.Vcpus
}

// GetVcpusOk returns a tuple with the Vcpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetVcpusOk() (*int32, bool) {
	if o == nil || IsNil(o.Vcpus) {
		return nil, false
	}
	return o.Vcpus, true
}

// HasVcpus returns a boolean if a field has been set.
func (o *VM) HasVcpus() bool {
	if o != nil && !IsNil(o.Vcpus) {
		return true
	}

	return false
}

// SetVcpus gets a reference to the given int32 and assigns it to the Vcpus field.
func (o *VM) SetVcpus(v int32) {
	o.Vcpus = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *VM) GetMemory() int32 {
	if o == nil || IsNil(o.Memory) {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *VM) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *VM) SetMemory(v int32) {
	o.Memory = &v
}

// GetAutostart returns the Autostart field value if set, zero value otherwise.
func (o *VM) GetAutostart() bool {
	if o == nil || IsNil(o.Autostart) {
		var ret bool
		return ret
	}
	return *o.Autostart
}

// GetAutostartOk returns a tuple with the Autostart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetAutostartOk() (*bool, bool) {
	if o == nil || IsNil(o.Autostart) {
		return nil, false
	}
	return o.Autostart, true
}

// HasAutostart returns a boolean if a field has been set.
func (o *VM) HasAutostart() bool {
	if o != nil && !IsNil(o.Autostart) {
		return true
	}

	return false
}

// SetAutostart gets a reference to the given bool and assigns it to the Autostart field.
func (o *VM) SetAutostart(v bool) {
	o.Autostart = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *VM) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *VM) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *VM) SetTime(v string) {
	o.Time = &v
}

// GetBootloader returns the Bootloader field value if set, zero value otherwise.
func (o *VM) GetBootloader() string {
	if o == nil || IsNil(o.Bootloader) {
		var ret string
		return ret
	}
	return *o.Bootloader
}

// GetBootloaderOk returns a tuple with the Bootloader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetBootloaderOk() (*string, bool) {
	if o == nil || IsNil(o.Bootloader) {
		return nil, false
	}
	return o.Bootloader, true
}

// HasBootloader returns a boolean if a field has been set.
func (o *VM) HasBootloader() bool {
	if o != nil && !IsNil(o.Bootloader) {
		return true
	}

	return false
}

// SetBootloader gets a reference to the given string and assigns it to the Bootloader field.
func (o *VM) SetBootloader(v string) {
	o.Bootloader = &v
}

// GetCores returns the Cores field value if set, zero value otherwise.
func (o *VM) GetCores() int32 {
	if o == nil || IsNil(o.Cores) {
		var ret int32
		return ret
	}
	return *o.Cores
}

// GetCoresOk returns a tuple with the Cores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetCoresOk() (*int32, bool) {
	if o == nil || IsNil(o.Cores) {
		return nil, false
	}
	return o.Cores, true
}

// HasCores returns a boolean if a field has been set.
func (o *VM) HasCores() bool {
	if o != nil && !IsNil(o.Cores) {
		return true
	}

	return false
}

// SetCores gets a reference to the given int32 and assigns it to the Cores field.
func (o *VM) SetCores(v int32) {
	o.Cores = &v
}

// GetThreads returns the Threads field value if set, zero value otherwise.
func (o *VM) GetThreads() int32 {
	if o == nil || IsNil(o.Threads) {
		var ret int32
		return ret
	}
	return *o.Threads
}

// GetThreadsOk returns a tuple with the Threads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetThreadsOk() (*int32, bool) {
	if o == nil || IsNil(o.Threads) {
		return nil, false
	}
	return o.Threads, true
}

// HasThreads returns a boolean if a field has been set.
func (o *VM) HasThreads() bool {
	if o != nil && !IsNil(o.Threads) {
		return true
	}

	return false
}

// SetThreads gets a reference to the given int32 and assigns it to the Threads field.
func (o *VM) SetThreads(v int32) {
	o.Threads = &v
}

// GetShutdownTimeout returns the ShutdownTimeout field value if set, zero value otherwise.
func (o *VM) GetShutdownTimeout() int32 {
	if o == nil || IsNil(o.ShutdownTimeout) {
		var ret int32
		return ret
	}
	return *o.ShutdownTimeout
}

// GetShutdownTimeoutOk returns a tuple with the ShutdownTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetShutdownTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.ShutdownTimeout) {
		return nil, false
	}
	return o.ShutdownTimeout, true
}

// HasShutdownTimeout returns a boolean if a field has been set.
func (o *VM) HasShutdownTimeout() bool {
	if o != nil && !IsNil(o.ShutdownTimeout) {
		return true
	}

	return false
}

// SetShutdownTimeout gets a reference to the given int32 and assigns it to the ShutdownTimeout field.
func (o *VM) SetShutdownTimeout(v int32) {
	o.ShutdownTimeout = &v
}

// GetDevices returns the Devices field value if set, zero value otherwise.
func (o *VM) GetDevices() []VMDevicesInner {
	if o == nil || IsNil(o.Devices) {
		var ret []VMDevicesInner
		return ret
	}
	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetDevicesOk() ([]VMDevicesInner, bool) {
	if o == nil || IsNil(o.Devices) {
		return nil, false
	}
	return o.Devices, true
}

// HasDevices returns a boolean if a field has been set.
func (o *VM) HasDevices() bool {
	if o != nil && !IsNil(o.Devices) {
		return true
	}

	return false
}

// SetDevices gets a reference to the given []VMDevicesInner and assigns it to the Devices field.
func (o *VM) SetDevices(v []VMDevicesInner) {
	o.Devices = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *VM) GetStatus() VMStatus {
	if o == nil || IsNil(o.Status) {
		var ret VMStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VM) GetStatusOk() (*VMStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *VM) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given VMStatus and assigns it to the Status field.
func (o *VM) SetStatus(v VMStatus) {
	o.Status = &v
}

func (o VM) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Vcpus) {
		toSerialize["vcpus"] = o.Vcpus
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Autostart) {
		toSerialize["autostart"] = o.Autostart
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Bootloader) {
		toSerialize["bootloader"] = o.Bootloader
	}
	if !IsNil(o.Cores) {
		toSerialize["cores"] = o.Cores
	}
	if !IsNil(o.Threads) {
		toSerialize["threads"] = o.Threads
	}
	if !IsNil(o.ShutdownTimeout) {
		toSerialize["shutdown_timeout"] = o.ShutdownTimeout
	}
	if !IsNil(o.Devices) {
		toSerialize["devices"] = o.Devices
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VM) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVM := _VM{}

	err = json.Unmarshal(bytes, &varVM)

	if err != nil {
		return err
	}

	*o = VM(varVM)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "vcpus")
		delete(additionalProperties, "memory")
		delete(additionalProperties, "autostart")
		delete(additionalProperties, "time")
		delete(additionalProperties, "bootloader")
		delete(additionalProperties, "cores")
		delete(additionalProperties, "threads")
		delete(additionalProperties, "shutdown_timeout")
		delete(additionalProperties, "devices")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVM struct {
	value *VM
	isSet bool
}

func (v NullableVM) Get() *VM {
	return v.value
}

func (v *NullableVM) Set(val *VM) {
	v.value = val
	v.isSet = true
}

func (v NullableVM) IsSet() bool {
	return v.isSet
}

func (v *NullableVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVM(val *VM) *NullableVM {
	return &NullableVM{value: val, isSet: true}
}

func (v NullableVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
