/*
TrueNAS RESTful API

Go SDK for interacting with TrueNAS APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// ISCSIPortalListenInner struct for ISCSIPortalListenInner
type ISCSIPortalListenInner struct {
	Ip string `json:"ip"`
	Port int32 `json:"port"`
}

// NewISCSIPortalListenInner instantiates a new ISCSIPortalListenInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewISCSIPortalListenInner(ip string, port int32) *ISCSIPortalListenInner {
	this := ISCSIPortalListenInner{}
	this.Ip = ip
	this.Port = port
	return &this
}

// NewISCSIPortalListenInnerWithDefaults instantiates a new ISCSIPortalListenInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewISCSIPortalListenInnerWithDefaults() *ISCSIPortalListenInner {
	this := ISCSIPortalListenInner{}
	return &this
}

// GetIp returns the Ip field value
func (o *ISCSIPortalListenInner) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *ISCSIPortalListenInner) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *ISCSIPortalListenInner) SetIp(v string) {
	o.Ip = v
}

// GetPort returns the Port field value
func (o *ISCSIPortalListenInner) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *ISCSIPortalListenInner) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *ISCSIPortalListenInner) SetPort(v int32) {
	o.Port = v
}

func (o ISCSIPortalListenInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ip"] = o.Ip
	}
	if true {
		toSerialize["port"] = o.Port
	}
	return json.Marshal(toSerialize)
}

type NullableISCSIPortalListenInner struct {
	value *ISCSIPortalListenInner
	isSet bool
}

func (v NullableISCSIPortalListenInner) Get() *ISCSIPortalListenInner {
	return v.value
}

func (v *NullableISCSIPortalListenInner) Set(val *ISCSIPortalListenInner) {
	v.value = val
	v.isSet = true
}

func (v NullableISCSIPortalListenInner) IsSet() bool {
	return v.isSet
}

func (v *NullableISCSIPortalListenInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableISCSIPortalListenInner(val *ISCSIPortalListenInner) *NullableISCSIPortalListenInner {
	return &NullableISCSIPortalListenInner{value: val, isSet: true}
}

func (v NullableISCSIPortalListenInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableISCSIPortalListenInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


