/*
TrueNAS RESTful API

Go SDK for interacting with TrueNAS APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// ISCSITarget struct for ISCSITarget
type ISCSITarget struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Alias NullableString `json:"alias"`
	Mode string `json:"mode"`
	Groups []ISCSITargetGroupsInner `json:"groups"`
}

// NewISCSITarget instantiates a new ISCSITarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewISCSITarget(id int32, name string, alias NullableString, mode string, groups []ISCSITargetGroupsInner) *ISCSITarget {
	this := ISCSITarget{}
	this.Id = id
	this.Name = name
	this.Alias = alias
	this.Mode = mode
	this.Groups = groups
	return &this
}

// NewISCSITargetWithDefaults instantiates a new ISCSITarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewISCSITargetWithDefaults() *ISCSITarget {
	this := ISCSITarget{}
	return &this
}

// GetId returns the Id field value
func (o *ISCSITarget) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ISCSITarget) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ISCSITarget) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ISCSITarget) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ISCSITarget) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ISCSITarget) SetName(v string) {
	o.Name = v
}

// GetAlias returns the Alias field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ISCSITarget) GetAlias() string {
	if o == nil || o.Alias.Get() == nil {
		var ret string
		return ret
	}

	return *o.Alias.Get()
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ISCSITarget) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alias.Get(), o.Alias.IsSet()
}

// SetAlias sets field value
func (o *ISCSITarget) SetAlias(v string) {
	o.Alias.Set(&v)
}

// GetMode returns the Mode field value
func (o *ISCSITarget) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *ISCSITarget) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *ISCSITarget) SetMode(v string) {
	o.Mode = v
}

// GetGroups returns the Groups field value
func (o *ISCSITarget) GetGroups() []ISCSITargetGroupsInner {
	if o == nil {
		var ret []ISCSITargetGroupsInner
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *ISCSITarget) GetGroupsOk() ([]ISCSITargetGroupsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *ISCSITarget) SetGroups(v []ISCSITargetGroupsInner) {
	o.Groups = v
}

func (o ISCSITarget) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["alias"] = o.Alias.Get()
	}
	if true {
		toSerialize["mode"] = o.Mode
	}
	if true {
		toSerialize["groups"] = o.Groups
	}
	return json.Marshal(toSerialize)
}

type NullableISCSITarget struct {
	value *ISCSITarget
	isSet bool
}

func (v NullableISCSITarget) Get() *ISCSITarget {
	return v.value
}

func (v *NullableISCSITarget) Set(val *ISCSITarget) {
	v.value = val
	v.isSet = true
}

func (v NullableISCSITarget) IsSet() bool {
	return v.isSet
}

func (v *NullableISCSITarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableISCSITarget(val *ISCSITarget) *NullableISCSITarget {
	return &NullableISCSITarget{value: val, isSet: true}
}

func (v NullableISCSITarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableISCSITarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


