/*
TrueNAS RESTful API

Go SDK for interacting with TrueNAS APIs (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// DeleteISCSIExtentParams struct for DeleteISCSIExtentParams
type DeleteISCSIExtentParams struct {
	Remove bool `json:"remove"`
	Force bool `json:"force"`
}

// NewDeleteISCSIExtentParams instantiates a new DeleteISCSIExtentParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteISCSIExtentParams(remove bool, force bool) *DeleteISCSIExtentParams {
	this := DeleteISCSIExtentParams{}
	this.Remove = remove
	this.Force = force
	return &this
}

// NewDeleteISCSIExtentParamsWithDefaults instantiates a new DeleteISCSIExtentParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteISCSIExtentParamsWithDefaults() *DeleteISCSIExtentParams {
	this := DeleteISCSIExtentParams{}
	return &this
}

// GetRemove returns the Remove field value
func (o *DeleteISCSIExtentParams) GetRemove() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Remove
}

// GetRemoveOk returns a tuple with the Remove field value
// and a boolean to check if the value has been set.
func (o *DeleteISCSIExtentParams) GetRemoveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Remove, true
}

// SetRemove sets field value
func (o *DeleteISCSIExtentParams) SetRemove(v bool) {
	o.Remove = v
}

// GetForce returns the Force field value
func (o *DeleteISCSIExtentParams) GetForce() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Force
}

// GetForceOk returns a tuple with the Force field value
// and a boolean to check if the value has been set.
func (o *DeleteISCSIExtentParams) GetForceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Force, true
}

// SetForce sets field value
func (o *DeleteISCSIExtentParams) SetForce(v bool) {
	o.Force = v
}

func (o DeleteISCSIExtentParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["remove"] = o.Remove
	}
	if true {
		toSerialize["force"] = o.Force
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteISCSIExtentParams struct {
	value *DeleteISCSIExtentParams
	isSet bool
}

func (v NullableDeleteISCSIExtentParams) Get() *DeleteISCSIExtentParams {
	return v.value
}

func (v *NullableDeleteISCSIExtentParams) Set(val *DeleteISCSIExtentParams) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteISCSIExtentParams) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteISCSIExtentParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteISCSIExtentParams(val *DeleteISCSIExtentParams) *NullableDeleteISCSIExtentParams {
	return &NullableDeleteISCSIExtentParams{value: val, isSet: true}
}

func (v NullableDeleteISCSIExtentParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteISCSIExtentParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


