/*
TrueNAS RESTful API

Testing IscsiTargetAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package truenas

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "github.com/terricain/truenas-go-sdk/pkg/truenas"
)

func Test_truenas_IscsiTargetAPIService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IscsiTargetAPIService CreateISCSITarget", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.IscsiTargetAPI.CreateISCSITarget(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IscsiTargetAPIService DeleteISCSITarget", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var id int32

		httpRes, err := apiClient.IscsiTargetAPI.DeleteISCSITarget(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IscsiTargetAPIService GetISCSITarget", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var id int32

		resp, httpRes, err := apiClient.IscsiTargetAPI.GetISCSITarget(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test IscsiTargetAPIService ListISCSITarget", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.IscsiTargetAPI.ListISCSITarget(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
